set(_AMENT_PACKAGE_NAME "rmw_gurumdds_cpp")
set(rmw_gurumdds_cpp_VERSION "5.0.0")
set(rmw_gurumdds_cpp_MAINTAINER "Donghee Lee <donghee@gurum.cc>, Hongsup Shim <hongsup@gurum.cc>")
set(rmw_gurumdds_cpp_BUILD_DEPENDS "gurumdds-2.8" "gurumdds_cmake_module" "rcutils" "rmw" "rmw_dds_common" "rosidl_runtime_c" "rosidl_runtime_cpp" "rosidl_generator_dds_idl" "rosidl_typesupport_introspection_c" "rosidl_typesupport_introspection_cpp")
set(rmw_gurumdds_cpp_BUILDTOOL_DEPENDS "ament_cmake_ros" "rosidl_cmake")
set(rmw_gurumdds_cpp_BUILD_EXPORT_DEPENDS "gurumdds-2.8" "gurumdds_cmake_module" "rmw_dds_common" "rosidl_runtime_c" "rosidl_runtime_cpp" "rosidl_typesupport_introspection_c" "rosidl_typesupport_introspection_cpp")
set(rmw_gurumdds_cpp_BUILDTOOL_EXPORT_DEPENDS )
set(rmw_gurumdds_cpp_EXEC_DEPENDS "rcutils" "rmw")
set(rmw_gurumdds_cpp_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(rmw_gurumdds_cpp_GROUP_DEPENDS )
set(rmw_gurumdds_cpp_MEMBER_OF_GROUPS "rmw_implementation_packages")
set(rmw_gurumdds_cpp_DEPRECATED "")
set(rmw_gurumdds_cpp_EXPORT_TAGS)
list(APPEND rmw_gurumdds_cpp_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
